AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  NotifyEmail:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-bucket-java-task/b43a57e37a1718f77fbee22d0f1509cf
      Description: ''
      MemorySize: 512
      Timeout: 15
      Handler: example.Hello::handleRequest
      Runtime: java11
      Architectures:
      - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
      - Statement:
        - Effect: Allow
          Action:
          - logs:CreateLogGroup
          Resource: arn:aws:logs:ap-south-1:977099009203:*
        - Effect: Allow
          Action:
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource:
          - arn:aws:logs:ap-south-1:977099009203:log-group:/aws/lambda/NotifyEmail:*
        - Effect: Allow
          Action:
          - ses:*
          Resource: '*'
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
  CloudWatchEventRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(1 day)
      Targets:
      - Arn:
          Fn::GetAtt:
          - NotifyEmail
          - Arn
        Id: LambdaTarget
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: NotifyEmail
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - CloudWatchEventRule
        - Arn
